/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 TentativeFirst.glb 
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGraph, GroupProps } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { GLTF } from 'three-stdlib'
import * as THREE from 'three';

type ModelProps = GroupProps;

interface FirstSongGLTF extends GLTF {
  animations: any[];
  nodes: {
    [key: string]: THREE.Object3D; 
    spine: THREE.SkinnedMesh; 
    root: THREE.SkinnedMesh;  
    'MCH-torsoparent': THREE.SkinnedMesh;
    'MCH-hand_ikparentL': THREE.SkinnedMesh;
    'MCH-upper_arm_ik_targetparentL': THREE.SkinnedMesh;
    'MCH-hand_ikparentR': THREE.SkinnedMesh;
    'MCH-upper_arm_ik_targetparentR': THREE.SkinnedMesh;
    'MCH-eye_commonparent': THREE.SkinnedMesh;
    'MCH-foot_ikparentL': THREE.SkinnedMesh;
    'MCH-thigh_ik_targetparentL': THREE.SkinnedMesh;
    'MCH-foot_ikparentR': THREE.SkinnedMesh;
    'MCH-thigh_ik_targetparentR': THREE.SkinnedMesh;
    'MCH-lip_armBL001': THREE.SkinnedMesh;
    'MCH-lip_armBR001': THREE.SkinnedMesh;
    'MCH-lip_armTL001': THREE.SkinnedMesh;
    'MCH-lip_armTR001': THREE.SkinnedMesh;
    back_low: THREE.SkinnedMesh; 
    Plane003: THREE.SkinnedMesh;
    Plane003_1: THREE.SkinnedMesh;
    Plane003_2: THREE.SkinnedMesh;
    body_low002: THREE.SkinnedMesh;
    body_low003: THREE.SkinnedMesh;
    pant_low: THREE.SkinnedMesh;
    tongue_low: THREE.SkinnedMesh;
    tshirt_low: THREE.SkinnedMesh;
  };
  materials: {
    [key: string]: THREE.Material;
  };
}


export function Model(props: ModelProps) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations }: FirstSongGLTF = useGLTF('/TentativeFirst.glb') as FirstSongGLTF;
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  const [isPlaying, setIsPlaying] = useState(false);
  
  const toggleAnimation = () => {
    if (isPlaying) {
      // check if first animation is running
      Object.values(actions).forEach(action => {
        if (action) {
          action.paused = true;
        }
      });
      setIsPlaying(false);
    } else {
      Object.values(actions).forEach(action => {
        if (action) {
          action.paused = false;
          action.play();
        }
      });
      setIsPlaying(true);
    }
  };

  useEffect(() => {
    if (animations.length > 0) {
      Object.values(actions).forEach(action => {
        action?.play();
      });
      setIsPlaying(true);
    }

    const handleToggleAnimation = () => {
      toggleAnimation();
    };

    window.addEventListener('toggleAnimation', handleToggleAnimation);

    return () => {
      Object.values(actions).forEach(action => {
        action?.stop();
      });
      window.removeEventListener('toggleAnimation', handleToggleAnimation);
    };
  }, [animations, actions, isPlaying]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig">
          <primitive object={nodes.spine} />
        </group>

        {/* Toggle button for animation */}
        <button onClick={() => toggleAnimation()} style={{
          position: 'absolute',
          top: '20px',
          left: '20px',
          padding: '10px',
          backgroundColor: 'black',
          color: 'white',
          border: 'none',
          cursor: 'pointer',
        }}>
          {isPlaying ? 'Stop Animation' : 'Play Animation'}
        </button>

        {/* MODEL */}
        <group name="rig">
          <primitive object={nodes.root} />
          <primitive object={nodes['MCH-torsoparent']} />
          <primitive object={nodes['MCH-hand_ikparentL']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentL']} />
          <primitive object={nodes['MCH-hand_ikparentR']} />
          <primitive object={nodes['MCH-upper_arm_ik_targetparentR']} />
          <primitive object={nodes['MCH-eye_commonparent']} />
          <primitive object={nodes['MCH-foot_ikparentL']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentL']} />
          <primitive object={nodes['MCH-foot_ikparentR']} />
          <primitive object={nodes['MCH-thigh_ik_targetparentR']} />
          <primitive object={nodes['MCH-lip_armBL001']} />
          <primitive object={nodes['MCH-lip_armBR001']} />
          <primitive object={nodes['MCH-lip_armTL001']} />
          <primitive object={nodes['MCH-lip_armTR001']} />
          <skinnedMesh name="back_low" 
          geometry={(nodes.back_low as THREE.SkinnedMesh).geometry} material={materials['Material.006']} skeleton={(nodes.back_low as THREE.SkinnedMesh).skeleton} />
          <group name="body_low">
            <skinnedMesh name="Plane003" geometry={(nodes.Plane003 as THREE.SkinnedMesh).geometry} material={materials.skin} skeleton={(nodes.Plane003 as THREE.SkinnedMesh).skeleton} />
            <skinnedMesh name="Plane003_1" geometry={(nodes.Plane003_1 as THREE.SkinnedMesh).geometry} material={materials.pupil} skeleton={(nodes.Plane003_1 as THREE.SkinnedMesh).skeleton} />
            <skinnedMesh name="Plane003_2" geometry={(nodes.Plane003_2 as THREE.SkinnedMesh).geometry} material={materials.lips} skeleton={(nodes.Plane003_2 as THREE.SkinnedMesh).skeleton} />
            <skinnedMesh name="Plane003_3" geometry={(nodes.Plane003_3 as THREE.SkinnedMesh).geometry} material={materials.shirt} skeleton={(nodes.Plane003_3 as THREE.SkinnedMesh).skeleton} />
          </group>
          <skinnedMesh name="body_low002" geometry={(nodes.body_low002 as THREE.SkinnedMesh).geometry} material={materials.pupil} skeleton={(nodes.body_low002 as THREE.SkinnedMesh).skeleton} />
          <skinnedMesh name="body_low003" geometry={(nodes.body_low003 as THREE.SkinnedMesh).geometry} material={materials.pupil} skeleton={(nodes.body_low003 as THREE.SkinnedMesh).skeleton} />
          <skinnedMesh name="pant_low" geometry={(nodes.pant_low as THREE.SkinnedMesh).geometry} material={materials.pants} skeleton={(nodes.pant_low as THREE.SkinnedMesh).skeleton} />
          <skinnedMesh name="tongue_low" geometry={(nodes.tongue_low as THREE.SkinnedMesh).geometry} material={materials.tongue} skeleton={(nodes.tongue_low as THREE.SkinnedMesh).skeleton} />
        </group>

        {/* ANIMATION */}
        <group name="BézierCircle" position={[0, 0.941, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.131} />
        <group name="WGT-rig_eyeL" position={[0.025, 0.619, 0.157]} rotation={[Math.PI / 2, 0, 0]} scale={0.016} />
        <group name="WGT-rig_eyeR" position={[-0.025, 0.619, 0.157]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.016} />
        <group name="WGT-rig_eyes" position={[0, 0.599, 0.136]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="WGT-rig_master_eyeL" position={[0.016, 0.599, 0.038]} rotation={[Math.PI, 0, Math.PI]} scale={0.008} />
        <group name="WGT-rig_master_eyeR" position={[-0.016, 0.599, 0.038]} rotation={[0, 0, Math.PI]} scale={-0.008} />
        <group name="WGT-rig_nose_master" position={[0, 0.592, 0.08]} rotation={[Math.PI, 0, Math.PI]} scale={0.027} />
        <group name="WGT-rig_earL" position={[0.055, 0.603, 0.005]} rotation={[1.639, -0.138, 0.22]} scale={0.024} />
        <group name="WGT-rig_earR" position={[-0.055, 0.603, 0.005]} rotation={[-1.503, -0.138, 0.22]} scale={-0.024} />
        <group name="WGT-rig_jaw_master" position={[0, 0.608, 0.03]} rotation={[-2.159, 0, 0]} scale={0.072} />
        <group name="WGT-rig_teethT" position={[0, 0.583, 0.078]} scale={0.022} />
        <group name="WGT-rig_teethB" position={[0, 0.568, 0.075]} scale={0.022} />
        <group name="WGT-rig_tongue_master" position={[0, 0.569, 0.035]} rotation={[-2.924, 0, 0]} scale={0.008} />
        <group name="WGT-rig_browBL" position={[0.042, 0.625, 0.057]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_browBL001" position={[0.036, 0.629, 0.064]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_browBL002" position={[0.029, 0.63, 0.068]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_browBL003" position={[0.018, 0.629, 0.072]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_browBL004" position={[0.009, 0.619, 0.07]} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
        <group name="WGT-rig_browBR" position={[-0.042, 0.625, 0.057]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.004} />
        <group name="WGT-rig_browBR001" position={[-0.036, 0.629, 0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.004} />
        <group name="WGT-rig_browBR002" position={[-0.029, 0.63, 0.068]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.004} />
        <group name="WGT-rig_browBR003" position={[-0.018, 0.629, 0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.004} />
        <group name="WGT-rig_browBR004" position={[-0.009, 0.619, 0.07]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.005} />
        <group name="WGT-rig_browTL" position={[0.05, 0.615, 0.046]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
        <group name="WGT-rig_browTL001" position={[0.043, 0.639, 0.061]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <group name="WGT-rig_browTL002" position={[0.028, 0.643, 0.073]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <group name="WGT-rig_browTL003" position={[0.011, 0.639, 0.078]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <group name="WGT-rig_browTR" position={[-0.05, 0.615, 0.046]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.011} />
        <group name="WGT-rig_browTR001" position={[-0.043, 0.639, 0.061]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.006} />
        <group name="WGT-rig_browTR002" position={[-0.028, 0.643, 0.073]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.006} />
        <group name="WGT-rig_browTR003" position={[-0.011, 0.639, 0.078]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.006} />
        <group name="WGT-rig_cheekBL001" position={[0.041, 0.582, 0.068]} rotation={[Math.PI / 2, 0, 0]} scale={0.011} />
        <group name="WGT-rig_cheekBR001" position={[-0.041, 0.582, 0.068]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.011} />
        <group name="WGT-rig_cheekTL001" position={[0.033, 0.596, 0.071]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="WGT-rig_cheekTR001" position={[-0.033, 0.596, 0.071]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01} />
        <group name="WGT-rig_chin" position={[0, 0.548, 0.07]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_chin001" position={[0, 0.558, 0.077]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_chin002" position={[0, 0.566, 0.051]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_chinL" position={[0.02, 0.552, 0.061]} rotation={[Math.PI / 2, 0, 0]} scale={0.012} />
        <group name="WGT-rig_chinR" position={[-0.02, 0.552, 0.061]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.012} />
        <group name="WGT-rig_earL002" position={[0.064, 0.631, -0.007]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
        <group name="WGT-rig_earL003" position={[0.061, 0.607, -0.008]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
        <group name="WGT-rig_earL004" position={[0.056, 0.591, 0.005]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
        <group name="WGT-rig_earR002" position={[-0.064, 0.631, -0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.007} />
        <group name="WGT-rig_earR003" position={[-0.061, 0.607, -0.008]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.007} />
        <group name="WGT-rig_earR004" position={[-0.056, 0.591, 0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.007} />
        <group name="WGT-rig_jaw" position={[0, 0.545, 0.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="WGT-rig_jawL" position={[0.055, 0.608, 0.03]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <group name="WGT-rig_jawL001" position={[0.04, 0.568, 0.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.012} />
        <group name="WGT-rig_jawR" position={[-0.055, 0.608, 0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.014} />
        <group name="WGT-rig_jawR001" position={[-0.04, 0.568, 0.033]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.012} />
        <group name="WGT-rig_lidBL" position={[0.014, 0.616, 0.067]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidBL001" position={[0.02, 0.611, 0.068]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidBL002" position={[0.028, 0.611, 0.067]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidBL003" position={[0.036, 0.613, 0.064]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidBR" position={[-0.014, 0.616, 0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lidBR001" position={[-0.02, 0.611, 0.068]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lidBR002" position={[-0.028, 0.611, 0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lidBR003" position={[-0.036, 0.613, 0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lidTL" position={[0.04, 0.618, 0.058]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidTL001" position={[0.035, 0.623, 0.064]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidTL002" position={[0.028, 0.625, 0.068]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidTL003" position={[0.019, 0.623, 0.068]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lidTR" position={[-0.04, 0.618, 0.058]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lidTR001" position={[-0.035, 0.623, 0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lidTR002" position={[-0.028, 0.625, 0.068]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lidTR003" position={[-0.019, 0.623, 0.068]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lipBL001" position={[0.01, 0.571, 0.082]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lipBR001" position={[-0.01, 0.571, 0.082]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lipTL001" position={[0.01, 0.577, 0.081]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lipsL" position={[0.011, 0.572, 0.047]} rotation={[Math.PI / 2, 0, -0.024]} scale={0.004} />
        <group name="WGT-rig_lipTR001" position={[-0.01, 0.577, 0.081]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_lipsR" position={[-0.011, 0.572, 0.047]} rotation={[-Math.PI / 2, 0, -0.024]} scale={-0.004} />
        <group name="WGT-rig_nose" position={[0, 0.625, 0.075]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <group name="WGT-rig_nose001" position={[0, 0.61, 0.076]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <group name="WGT-rig_nose002" position={[0, 0.597, 0.09]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} />
        <group name="WGT-rig_nose003" position={[0, 0.591, 0.089]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} />
        <group name="WGT-rig_nose004" position={[0, 0.585, 0.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.002} />
        <group name="WGT-rig_nose005" position={[0, 0.577, 0.054]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_noseL" position={[0.009, 0.608, 0.072]} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
        <group name="WGT-rig_noseL001" position={[0.009, 0.592, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
        <group name="WGT-rig_noseR" position={[-0.009, 0.608, 0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.005} />
        <group name="WGT-rig_noseR001" position={[-0.009, 0.592, 0.08]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.005} />
        <group name="WGT-rig_tongue" position={[0, 0.573, 0.056]} rotation={[-2.924, 0, 0]} scale={0.013} />
        <group name="WGT-rig_tongue001" position={[0, 0.569, 0.035]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_tongue002" position={[0, 0.568, 0.024]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_tongue003" position={[0, 0.559, 0.017]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_lipT" position={[0, 0.577, 0.084]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lipB" position={[0, 0.569, 0.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_spine_fk" position={[0, 0.347, -0.005]} rotation={[1.838, 0, 0]} scale={0.061} />
        <group name="WGT-rig_spine_fk001" position={[0, 0.405, 0]} rotation={[1.663, 0, 0]} scale={0.058} />
        <group name="WGT-rig_spine_fk002" position={[0, 0.405, 0]} rotation={[1.541, 0, 0]} scale={0.059} />
        <group name="WGT-rig_spine_fk003" position={[0, 0.464, -0.002]} rotation={[1.542, 0, 0]} scale={0.061} />
        <group name="WGT-rig_tweak_spine" position={[0, 0.289, -0.021]} rotation={[1.838, 0, 0]} scale={0.03} />
        <group name="WGT-rig_tweak_spine001" position={[0, 0.347, -0.005]} rotation={[1.663, 0, 0]} scale={0.029} />
        <group name="WGT-rig_tweak_spine002" position={[0, 0.405, 0]} rotation={[1.541, 0, 0]} scale={0.029} />
        <group name="WGT-rig_tweak_spine003" position={[0, 0.464, -0.002]} rotation={[1.542, 0, 0]} scale={0.03} />
        <group name="WGT-rig_tweak_spine004" position={[0, 0.524, -0.004]} rotation={[1.948, 0, 0]} scale={0.01} />
        <group name="WGT-rig_torso" position={[0, 0.318, -0.013]} scale={0.143} />
        <group name="WGT-rig_hips" position={[0, 0.289, -0.021]} rotation={[1.838, 0, 0]} scale={0.059} />
        <group name="WGT-rig_chest" position={[0, 0.464, -0.002]} rotation={[1.542, 0, 0]} scale={0.079} />
        <group name="WGT-rig_breastL" position={[0.032, 0.462, -0.015]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.044} />
        <group name="WGT-rig_breastR" position={[-0.032, 0.462, -0.015]} rotation={[0, 0, -Math.PI]} scale={-0.044} />
        <group name="WGT-rig_shoulderL" position={[0.006, 0.508, 0.022]} rotation={[-0.001, -1.039, -0.001]} scale={0.055} />
        <group name="WGT-rig_upper_arm_parentL" position={[0.062, 0.501, -0.008]} rotation={[-1.465, -0.655, -2.909]} scale={0.024} />
        <group name="WGT-rig_upper_arm_fkL" position={[0.062, 0.501, -0.008]} rotation={[-1.465, -0.655, -2.909]} scale={0.098} />
        <group name="WGT-rig_forearm_fkL" position={[0.121, 0.424, -0.017]} rotation={[-1.871, -0.689, 3.119]} scale={0.089} />
        <group name="WGT-rig_hand_fkL" position={[0.178, 0.359, 0.004]} rotation={[-1.782, -0.637, -3.107]} scale={0.025} />
        <group name="WGT-rig_upper_arm_ikL" position={[0.062, 0.501, -0.008]} rotation={[-1.465, -0.655, -2.909]} scale={0.098} />
        <group name="WGT-rig_upper_arm_ik_targetL" position={[0.105, 0.396, -0.197]} rotation={[2.985, -0.089, 1.027]} scale={0.023} />
        <group name="WGT-rig_hand_ikL" position={[0.178, 0.359, 0.004]} rotation={[-1.782, -0.637, -3.107]} scale={0.025} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleL" position={[0.121, 0.424, -0.017]} rotation={[Math.PI / 2, 0, -2.258]} scale={0.184} />
        <group name="WGT-rig_upper_arm_tweakL" position={[0.062, 0.501, -0.008]} rotation={[-1.465, -0.655, -2.909]} scale={0.024} />
        <group name="WGT-rig_upper_arm_tweakL001" position={[0.092, 0.463, -0.013]} rotation={[-1.465, -0.655, -2.909]} scale={0.024} />
        <group name="WGT-rig_forearm_tweakL" position={[0.121, 0.424, -0.017]} rotation={[-1.871, -0.689, 3.119]} scale={0.022} />
        <group name="WGT-rig_forearm_tweakL001" position={[0.149, 0.392, -0.006]} rotation={[-1.871, -0.689, 3.119]} scale={0.022} />
        <group name="WGT-rig_hand_tweakL" position={[0.178, 0.359, 0.004]} rotation={[-1.782, -0.637, -3.107]} scale={0.006} />
        <group name="WGT-rig_palmL" position={[0.186, 0.35, -0.002]} rotation={[-1.545, -0.589, 1.597]} scale={0.023} />
        <group name="WGT-rig_f_index01L" position={[0.196, 0.332, 0.02]} rotation={[-1.744, -0.517, 1.069]} scale={0.013} />
        <group name="WGT-rig_f_index02L" position={[0.202, 0.321, 0.022]} rotation={[-1.691, -0.421, 1.093]} scale={0.008} />
        <group name="WGT-rig_f_index03L" position={[0.205, 0.314, 0.023]} rotation={[-1.684, -0.425, 1.095]} scale={0.008} />
        <group name="WGT-rig_f_index01L001" position={[0.208, 0.307, 0.023]} rotation={[1.457, 0.425, 1.189]} scale={0.004} />
        <group name="WGT-rig_f_index01_masterL" position={[0.196, 0.332, 0.02]} rotation={[-1.744, -0.517, 1.069]} scale={0.047} />
        <group name="WGT-rig_thumb01L" position={[0.177, 0.348, 0.013]} rotation={[-2.022, 0.02, -1.168]} scale={0.015} />
        <group name="WGT-rig_thumb02L" position={[0.177, 0.335, 0.019]} rotation={[-1.912, -0.383, -1.16]} scale={0.01} />
        <group name="WGT-rig_thumb03L" position={[0.181, 0.326, 0.022]} rotation={[-1.676, -0.512, -1.056]} scale={0.008} />
        <group name="WGT-rig_thumb01L001" position={[0.185, 0.319, 0.023]} rotation={[1.466, 0.512, -0.953]} scale={0.004} />
        <group name="WGT-rig_thumb01_masterL" position={[0.177, 0.348, 0.013]} rotation={[-2.022, 0.02, -1.168]} scale={0.055} />
        <group name="WGT-rig_f_middle01L" position={[0.198, 0.331, 0.012]} rotation={[-1.785, -0.628, 1.328]} scale={0.014} />
        <group name="WGT-rig_f_middle02L" position={[0.206, 0.32, 0.015]} rotation={[-1.746, -0.438, 1.349]} scale={0.008} />
        <group name="WGT-rig_f_middle03L" position={[0.21, 0.313, 0.016]} rotation={[-1.697, -0.333, 1.368]} scale={0.008} />
        <group name="WGT-rig_f_middle01L001" position={[0.212, 0.306, 0.017]} rotation={[1.445, 0.333, 1.451]} scale={0.004} />
        <group name="WGT-rig_f_middle01_masterL" position={[0.198, 0.331, 0.012]} rotation={[-1.785, -0.628, 1.328]} scale={0.051} />
        <group name="WGT-rig_f_ring01L" position={[0.2, 0.332, 0.005]} rotation={[-1.82, -0.5, 1.183]} scale={0.013} />
        <group name="WGT-rig_f_ring02L" position={[0.206, 0.321, 0.007]} rotation={[-1.779, -0.431, 1.201]} scale={0.008} />
        <group name="WGT-rig_f_ring03L" position={[0.209, 0.314, 0.009]} rotation={[-1.788, -0.405, 1.197]} scale={0.007} />
        <group name="WGT-rig_f_ring01L001" position={[0.211, 0.308, 0.01]} rotation={[1.353, 0.405, 1.37]} scale={0.003} />
        <group name="WGT-rig_f_ring01_masterL" position={[0.2, 0.332, 0.005]} rotation={[-1.82, -0.5, 1.183]} scale={0.046} />
        <group name="WGT-rig_f_pinky01L" position={[0.199, 0.331, -0.002]} rotation={[-1.815, -0.474, 1.282]} scale={0.009} />
        <group name="WGT-rig_f_pinky02L" position={[0.203, 0.323, 0]} rotation={[-1.79, -0.449, 1.293]} scale={0.008} />
        <group name="WGT-rig_f_pinky03L" position={[0.206, 0.317, 0.001]} rotation={[-1.748, -0.185, 1.306]} scale={0.006} />
        <group name="WGT-rig_f_pinky01L001" position={[0.208, 0.311, 0.002]} rotation={[1.393, 0.185, 1.372]} scale={0.003} />
        <group name="WGT-rig_f_pinky01_masterL" position={[0.199, 0.331, -0.002]} rotation={[-1.815, -0.474, 1.282]} scale={0.037} />
        <group name="WGT-rig_shoulderR" position={[-0.006, 0.508, 0.022]} rotation={[3.14, -1.039, -0.001]} scale={-0.055} />
        <group name="WGT-rig_upper_arm_parentR" position={[-0.062, 0.501, -0.008]} rotation={[1.676, -0.655, -2.909]} scale={-0.024} />
        <group name="WGT-rig_upper_arm_fkR" position={[-0.062, 0.501, -0.008]} rotation={[1.676, -0.655, -2.909]} scale={-0.098} />
        <group name="WGT-rig_forearm_fkR" position={[-0.121, 0.424, -0.017]} rotation={[1.27, -0.689, 3.119]} scale={-0.089} />
        <group name="WGT-rig_hand_fkR" position={[-0.178, 0.359, 0.004]} rotation={[1.36, -0.637, -3.107]} scale={-0.025} />
        <group name="WGT-rig_upper_arm_ikR" position={[-0.062, 0.501, -0.008]} rotation={[1.676, -0.655, -2.909]} scale={-0.098} />
        <group name="WGT-rig_upper_arm_ik_targetR" position={[-0.105, 0.396, -0.197]} rotation={[-0.157, -0.089, 1.027]} scale={-0.023} />
        <group name="WGT-rig_hand_ikR" position={[-0.178, 0.359, 0.004]} rotation={[1.36, -0.637, -3.107]} scale={-0.025} />
        <group name="WGT-rig_VIS_upper_arm_ik_poleR" position={[-0.121, 0.424, -0.017]} rotation={[-Math.PI / 2, 0, -2.258]} scale={-0.184} />
        <group name="WGT-rig_upper_arm_tweakR" position={[-0.062, 0.501, -0.008]} rotation={[1.676, -0.655, -2.909]} scale={-0.024} />
        <group name="WGT-rig_upper_arm_tweakR001" position={[-0.092, 0.463, -0.013]} rotation={[1.676, -0.655, -2.909]} scale={-0.024} />
        <group name="WGT-rig_forearm_tweakR" position={[-0.121, 0.424, -0.017]} rotation={[1.27, -0.689, 3.119]} scale={-0.022} />
        <group name="WGT-rig_forearm_tweakR001" position={[-0.149, 0.392, -0.006]} rotation={[1.27, -0.689, 3.119]} scale={-0.022} />
        <group name="WGT-rig_hand_tweakR" position={[-0.178, 0.359, 0.004]} rotation={[1.36, -0.637, -3.107]} scale={-0.006} />
        <group name="WGT-rig_palmR" position={[-0.186, 0.35, -0.002]} rotation={[1.596, -0.589, 1.597]} scale={-0.023} />
        <group name="WGT-rig_f_index01R" position={[-0.196, 0.332, 0.02]} rotation={[1.398, -0.517, 1.069]} scale={-0.013} />
        <group name="WGT-rig_f_index02R" position={[-0.202, 0.321, 0.022]} rotation={[1.451, -0.421, 1.093]} scale={-0.008} />
        <group name="WGT-rig_f_index03R" position={[-0.205, 0.314, 0.023]} rotation={[1.457, -0.425, 1.095]} scale={-0.008} />
        <group name="WGT-rig_f_index01R001" position={[-0.208, 0.307, 0.023]} rotation={[-1.684, 0.425, 1.189]} scale={-0.004} />
        <group name="WGT-rig_f_index01_masterR" position={[-0.196, 0.332, 0.02]} rotation={[1.398, -0.517, 1.069]} scale={-0.047} />
        <group name="WGT-rig_thumb01R" position={[-0.177, 0.348, 0.013]} rotation={[1.12, 0.02, -1.168]} scale={-0.015} />
        <group name="WGT-rig_thumb02R" position={[-0.177, 0.335, 0.019]} rotation={[1.23, -0.383, -1.16]} scale={-0.01} />
        <group name="WGT-rig_thumb03R" position={[-0.181, 0.326, 0.022]} rotation={[1.466, -0.512, -1.056]} scale={-0.008} />
        <group name="WGT-rig_thumb01R001" position={[-0.185, 0.319, 0.023]} rotation={[-1.676, 0.512, -0.953]} scale={-0.004} />
        <group name="WGT-rig_thumb01_masterR" position={[-0.177, 0.348, 0.013]} rotation={[1.12, 0.02, -1.168]} scale={-0.055} />
        <group name="WGT-rig_f_middle01R" position={[-0.198, 0.331, 0.012]} rotation={[1.357, -0.628, 1.328]} scale={-0.014} />
        <group name="WGT-rig_f_middle02R" position={[-0.206, 0.32, 0.015]} rotation={[1.396, -0.438, 1.349]} scale={-0.008} />
        <group name="WGT-rig_f_middle03R" position={[-0.21, 0.313, 0.016]} rotation={[1.445, -0.333, 1.368]} scale={-0.008} />
        <group name="WGT-rig_f_middle01R001" position={[-0.212, 0.306, 0.017]} rotation={[-1.697, 0.333, 1.451]} scale={-0.004} />
        <group name="WGT-rig_f_middle01_masterR" position={[-0.198, 0.331, 0.012]} rotation={[1.357, -0.628, 1.328]} scale={-0.051} />
        <group name="WGT-rig_f_ring01R" position={[-0.2, 0.332, 0.005]} rotation={[1.322, -0.5, 1.183]} scale={-0.013} />
        <group name="WGT-rig_f_ring02R" position={[-0.206, 0.321, 0.007]} rotation={[1.363, -0.431, 1.201]} scale={-0.008} />
        <group name="WGT-rig_f_ring03R" position={[-0.209, 0.314, 0.009]} rotation={[1.353, -0.405, 1.197]} scale={-0.007} />
        <group name="WGT-rig_f_ring01R001" position={[-0.211, 0.308, 0.01]} rotation={[-1.788, 0.405, 1.37]} scale={-0.003} />
        <group name="WGT-rig_f_ring01_masterR" position={[-0.2, 0.332, 0.005]} rotation={[1.322, -0.5, 1.183]} scale={-0.046} />
        <group name="WGT-rig_f_pinky01R" position={[-0.199, 0.331, -0.002]} rotation={[1.327, -0.474, 1.282]} scale={-0.009} />
        <group name="WGT-rig_f_pinky02R" position={[-0.203, 0.323, 0]} rotation={[1.352, -0.449, 1.293]} scale={-0.008} />
        <group name="WGT-rig_f_pinky03R" position={[-0.206, 0.317, 0.001]} rotation={[1.393, -0.185, 1.306]} scale={-0.006} />
        <group name="WGT-rig_f_pinky01R001" position={[-0.208, 0.311, 0.002]} rotation={[-1.748, 0.185, 1.372]} scale={-0.003} />
        <group name="WGT-rig_f_pinky01_masterR" position={[-0.199, 0.331, -0.002]} rotation={[1.327, -0.474, 1.282]} scale={-0.037} />
        <group name="WGT-rig_neck" position={[0, 0.524, -0.004]} rotation={[1.856, 0, 0]} scale={0.041} />
        <group name="WGT-rig_head" position={[0, 0.563, 0.008]} rotation={[Math.PI / 2, 0, 0]} scale={0.117} />
        <group name="WGT-rig_tweak_spine005" position={[0, 0.544, 0.004]} rotation={[1.758, 0, 0]} scale={0.01} />
        <group name="WGT-rig_thigh_parentL" position={[0.031, 0.309, -0.008]} rotation={[-1.676, -0.101, 0.359]} scale={0.036} />
        <group name="WGT-rig_thigh_fkL" position={[0.031, 0.309, -0.008]} rotation={[-1.676, -0.101, 0.359]} scale={0.143} />
        <group name="WGT-rig_shin_fkL" position={[0.045, 0.168, 0.007]} rotation={[-1.407, 0.003, 0.372]} scale={0.149} />
        <group name="WGT-rig_foot_fkL" position={[0.045, 0.021, -0.017]} rotation={[-2.818, 0, 0.003]} scale={0.049} />
        <group name="WGT-rig_toe_fkL" position={[0.045, 0.005, 0.03]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.026} />
        <group name="WGT-rig_thigh_ikL" position={[0.031, 0.309, -0.008]} rotation={[-1.676, -0.101, 0.359]} scale={0.143} />
        <group name="WGT-rig_thigh_ik_targetL" position={[0.149, 0.164, 0.276]} rotation={[0.014, 0.369, -0.003]} scale={0.036} />
        <group name="WGT-rig_foot_ikL" position={[0.045, 0.021, -0.017]} scale={0.049} />
        <group name="WGT-rig_VIS_thigh_ik_poleL" position={[0.045, 0.168, 0.007]} rotation={[Math.PI / 2, 0, 0.37]} scale={0.288} />
        <group name="WGT-rig_thigh_tweakL" position={[0.031, 0.309, -0.008]} rotation={[-1.676, -0.101, 0.359]} scale={0.036} />
        <group name="WGT-rig_thigh_tweakL001" position={[0.038, 0.238, 0]} rotation={[-1.676, -0.101, 0.359]} scale={0.036} />
        <group name="WGT-rig_shin_tweakL" position={[0.045, 0.168, 0.007]} rotation={[-1.407, 0.003, 0.372]} scale={0.037} />
        <group name="WGT-rig_shin_tweakL001" position={[0.045, 0.094, -0.005]} rotation={[-1.407, 0.003, 0.372]} scale={0.037} />
        <group name="WGT-rig_foot_tweakL" position={[0.045, 0.021, -0.017]} rotation={[-2.818, 0, 0.003]} scale={0.012} />
        <group name="WGT-rig_foot_spin_ikL" position={[0.045, 0.005, 0.03]} scale={0.025} />
        <group name="WGT-rig_foot_heel_ikL" position={[0.045, 0.021, -0.017]} scale={0.025} />
        <group name="WGT-rig_toe_ikL" position={[0.045, 0.005, 0.03]} rotation={[Math.PI, 0, Math.PI]} scale={0.026} />
        <group name="WGT-rig_thigh_parentR" position={[-0.031, 0.309, -0.008]} rotation={[1.466, -0.101, 0.359]} scale={-0.036} />
        <group name="WGT-rig_thigh_fkR" position={[-0.031, 0.309, -0.008]} rotation={[1.466, -0.101, 0.359]} scale={-0.143} />
        <group name="WGT-rig_shin_fkR" position={[-0.045, 0.168, 0.007]} rotation={[1.735, 0.003, 0.372]} scale={-0.149} />
        <group name="WGT-rig_foot_fkR" position={[-0.045, 0.021, -0.017]} rotation={[0.324, 0, -0.003]} scale={-0.049} />
        <group name="WGT-rig_toe_fkR" position={[-0.045, 0.005, 0.03]} rotation={[0, 0, Math.PI]} scale={-0.026} />
        <group name="WGT-rig_thigh_ikR" position={[-0.031, 0.309, -0.008]} rotation={[1.466, -0.101, 0.359]} scale={-0.143} />
        <group name="WGT-rig_thigh_ik_targetR" position={[-0.149, 0.164, 0.276]} rotation={[-3.128, 0.369, -0.003]} scale={-0.036} />
        <group name="WGT-rig_foot_ikR" position={[-0.045, 0.021, -0.017]} rotation={[-Math.PI, 0, 0]} scale={-0.049} />
        <group name="WGT-rig_VIS_thigh_ik_poleR" position={[-0.045, 0.168, 0.007]} rotation={[-Math.PI / 2, 0, 0.37]} scale={-0.288} />
        <group name="WGT-rig_thigh_tweakR" position={[-0.031, 0.309, -0.008]} rotation={[1.466, -0.101, 0.359]} scale={-0.036} />
        <group name="WGT-rig_thigh_tweakR001" position={[-0.038, 0.238, 0]} rotation={[1.466, -0.101, 0.359]} scale={-0.036} />
        <group name="WGT-rig_shin_tweakR" position={[-0.045, 0.168, 0.007]} rotation={[1.735, 0.003, 0.372]} scale={-0.037} />
        <group name="WGT-rig_shin_tweakR001" position={[-0.045, 0.094, -0.005]} rotation={[1.735, 0.003, 0.372]} scale={-0.037} />
        <group name="WGT-rig_foot_tweakR" position={[-0.045, 0.021, -0.017]} rotation={[0.324, 0, -0.003]} scale={-0.012} />
        <group name="WGT-rig_foot_spin_ikR" position={[-0.045, 0.005, 0.03]} rotation={[-Math.PI, 0, 0]} scale={-0.025} />
        <group name="WGT-rig_foot_heel_ikR" position={[-0.045, 0.021, -0.017]} rotation={[-Math.PI, 0, 0]} scale={-0.025} />
        <group name="WGT-rig_toe_ikR" position={[-0.045, 0.005, 0.03]} rotation={[0, 0, Math.PI]} scale={-0.026} />
        <group name="WGT-rig_root" scale={0.289} />
        <group name="WGT-rig_eye_common" position={[0, 0.619, 0.157]} rotation={[Math.PI / 2, 0, 0]} scale={0.016} />
        <group name="WGT-rig_eye_masterL" position={[0.025, 0.619, 0.063]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.021} />
        <group name="WGT-rig_eye_masterR" position={[-0.025, 0.619, 0.063]} rotation={[0, 0, -Math.PI]} scale={-0.021} />
        <group name="WGT-rig_jaw_master_mouth" position={[0, 0.573, 0.083]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.035} />
        <group name="WGT-rig_tweak_tongue" position={[0, 0.57, 0.068]} rotation={[0.218, 0, 0]} scale={0.006} />
        <group name="WGT-rig_tweak_tongue001" position={[0, 0.573, 0.056]} rotation={[-0.155, 0, 0]} scale={0.008} />
        <group name="WGT-rig_tweak_tongue002" position={[0, 0.57, 0.039]} rotation={[-0.891, 0, 0]} scale={0.009} />
        <group name="WGT-rig_tweak_tongue003" position={[0, 0.557, 0.028]} rotation={[-0.891, 0, 0]} scale={0.009} />
        <group name="WGT-rig_lip_endL001" position={[0.017, 0.574, 0.075]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_lip_endR001" position={[-0.017, 0.574, 0.075]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.003} />
        <group name="WGT-rig_earL001" position={[0.058, 0.627, 0.007]} rotation={[Math.PI / 2, 0, 0]} scale={0.005} />
        <group name="WGT-rig_ear_endL004" position={[0.055, 0.603, 0.005]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
        <group name="WGT-rig_earR001" position={[-0.058, 0.627, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.005} />
        <group name="WGT-rig_ear_endR004" position={[-0.055, 0.603, 0.005]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.004} />
        <group name="WGT-rig_foreheadL" position={[0.014, 0.667, 0.072]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="WGT-rig_foreheadL001" position={[0.032, 0.666, 0.066]} rotation={[Math.PI / 2, 0, 0]} scale={0.008} />
        <group name="WGT-rig_foreheadL002" position={[0.048, 0.655, 0.047]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
        <group name="WGT-rig_foreheadR" position={[-0.014, 0.667, 0.072]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.01} />
        <group name="WGT-rig_foreheadR001" position={[-0.032, 0.666, 0.066]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.008} />
        <group name="WGT-rig_foreheadR002" position={[-0.048, 0.655, 0.047]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.007} />
        <group name="WGT-rig_chin_end001" position={[0, 0.565, 0.08]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
        <group name="WGT-rig_nose_end004" position={[0, 0.581, 0.083]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
        <group name="WGT-rig_templeL" position={[0.054, 0.648, 0.029]} rotation={[Math.PI / 2, 0, 0]} scale={0.014} />
        <group name="WGT-rig_templeR" position={[-0.054, 0.648, 0.029]} rotation={[-Math.PI / 2, 0, 0]} scale={-0.014} />
      </group>
    </group>
  )
}

useGLTF.preload('/firstAnimate.glb')